plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/home/clawd/.openclaw/workspace/websites/style7-perfection"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]